/**
 * OHLC candle series for the claim trading terminal.
 *
 * Why this module exists
 * ----------------------
 * The terminal originally rendered a hand-authored SVG with ~28 hardcoded
 * candles and a fixed price axis. The timeframe buttons changed their own
 * highlight and nothing else, so the "chart" showed the same picture at 15M and
 * at 1W. That is a decorative image, not a chart, and it would be caught
 * immediately by anyone who clicked the tabs.
 *
 * What this module produces instead
 * ---------------------------------
 * A real OHLC series where every value is *derived* from the project's own
 * numbers: the order book mid, the seller asks, the funding deadline and the
 * milestone schedule. Nothing is typed in as a literal price.
 *
 *   - The anchor price is the order book mid, so the chart agrees with the
 *     ladder rendered next to it on the same screen.
 *   - History is generated by a seeded PRNG (xorshift32 seeded from the project
 *     id), so the same project always produces the same series. A chart that
 *     reshuffles on every render is untrustworthy even in a demo.
 *   - Milestone events nudge the series on the candle they land in, so the
 *     marker pins drawn at those timestamps sit on a visible move.
 *
 * IMPORTANT - this is synthetic history, not market data. There is no indexer
 * behind it and no trades have occurred. Every screen that renders these candles
 * must label them as simulated; see `CANDLE_SERIES_IS_SYNTHETIC`.
 */

import type { OrderBook, Project } from '@protorwa/shared';

/** Machine-readable flag so callers cannot render candles without saying so. */
export const CANDLE_SERIES_IS_SYNTHETIC = true as const;

export interface Candle {
  /** Candle open time (ms since epoch). */
  t: number;
  /** Open price in USDG (dollars, not base units). */
  o: number;
  /** High price in USDG. */
  h: number;
  /** Low price in USDG. */
  l: number;
  /** Close price in USDG. */
  c: number;
  /** Traded volume in claim units. */
  v: number;
}

export interface MilestoneMarker {
  index: number;
  title: string;
  /** Timestamp the marker is drawn at. */
  t: number;
  status: Project['milestones'][number]['status'];
}

export interface CandleSeries {
  candles: Candle[];
  markers: MilestoneMarker[];
  /** Candle interval in milliseconds. */
  intervalMs: number;
  /** Number of candles, for axis labelling. */
  count: number;
}

export type Timeframe = '15M' | '1H' | '4H' | '1D' | '1W';

/**
 * Candle interval per timeframe.
 *
 * One "timeframe" means one candle, so a 15M chart is a series of 15-minute
 * candles. 96 candles per series keeps the plot readable at every zoom without
 * the bars collapsing into a solid block on a narrow viewport.
 */
export const TIMEFRAMES: Record<Timeframe, { label: string; intervalMs: number; candles: number }> = {
  '15M': { label: '15 minutes', intervalMs: 15 * 60_000, candles: 96 },
  '1H': { label: '1 hour', intervalMs: 60 * 60_000, candles: 96 },
  '4H': { label: '4 hours', intervalMs: 4 * 60 * 60_000, candles: 72 },
  '1D': { label: '1 day', intervalMs: 24 * 60 * 60_000, candles: 90 },
  '1W': { label: '1 week', intervalMs: 7 * 24 * 60 * 60_000, candles: 52 },
};

/** Shared empty series, so a missing project cannot crash a screen. */
const EMPTY_SERIES: CandleSeries = {
  candles: [],
  markers: [],
  intervalMs: TIMEFRAMES['1H'].intervalMs,
  count: 0,
};

/**
 * xorshift32.
 *
 * Chosen over `Math.random()` so a series is reproducible, and over a hash of
 * the index alone because that produces a visibly periodic sawtooth that reads
 * as a bug. Seeded per project, so project 1 and project 3 have distinct but
 * stable histories.
 */
function xorshift32(seed: number): () => number {
  let state = seed | 0 || 0x9e3779b9;
  return () => {
    state ^= state << 13;
    state ^= state >>> 17;
    state ^= state << 5;
    // Map to [0, 1) using the unsigned interpretation.
    return (state >>> 0) / 0x1_0000_0000;
  };
}

/**
 * Converts a USDG base-unit string to a dollar number for plotting.
 *
 * USDG has 6 decimals (it is a stablecoin pegged ~1:1 to the dollar), so a
 * claim at `5_000_000` base units plots as `5`. The prior ETH convention divided
 * by 1e18, which collapsed every USDG price to ~0 on the axis.
 */
function usdgToNumber(baseUnits: string): number {
  try {
    return Number(BigInt(baseUnits || '0')) / 1e6;
  } catch {
    return 0;
  }
}

/**
 * Derives the anchor price for a project from its own order book.
 *
 * Prefers the mid of best bid / best ask (what the ladder beside the chart
 * shows), falls back to the best ask, then to the claim price. All three are
 * real project fields, so the chart and the rest of the screen agree.
 */
export function anchorPrice(project: Project, book?: OrderBook): number {
  const bestAsk = book?.asks[0] ? usdgToNumber(book.asks[0].pricePerUnit) : 0;
  const bestBid = book?.bids[0] ? usdgToNumber(book.bids[0].pricePerUnit) : 0;

  if (bestAsk > 0 && bestBid > 0) return (bestAsk + bestBid) / 2;
  if (bestAsk > 0) return bestAsk;
  if (bestBid > 0) return bestBid;

  const claimPrice = usdgToNumber(project.claimPrice);
  return claimPrice > 0 ? claimPrice : 0.01;
}

/**
 * Builds an OHLC series for a project at a given timeframe.
 *
 * The series walks *backwards* from the anchor price so the final candle's close
 * equals the live mid: the rightmost candle is "now". Generating forwards from a
 * starting price would leave the chart's last price disagreeing with the stat
 * ribbon above it.
 */
export function buildCandleSeries(
  project: Project,
  timeframe: Timeframe,
  book?: OrderBook,
  now: number = Date.now(),
): CandleSeries {
  const config = TIMEFRAMES[timeframe];
  if (!config) return EMPTY_SERIES;

  const { intervalMs, candles: count } = config;
  const end = Math.floor(now / intervalMs) * intervalMs;

  const seedBase = Number.parseInt(project.id, 10);
  const rng = xorshift32(
    (Number.isFinite(seedBase) ? seedBase : project.slug.length) * 2654435761 +
      timeframe.charCodeAt(0) * 40503,
  );

  /**
   * A project with no book and no claim price has nothing to plot. Checked
   * explicitly rather than via `anchorPrice`, whose fallback deliberately
   * returns a usable default; that default is right for display and wrong as a
   * liveness test.
   */
  const hasAsk = Boolean(book?.asks[0] && usdgToNumber(book.asks[0].pricePerUnit) > 0);
  const hasBid = Boolean(book?.bids[0] && usdgToNumber(book.bids[0].pricePerUnit) > 0);
  const hasClaimPrice = usdgToNumber(project.claimPrice) > 0;
  if (!hasAsk && !hasBid && !hasClaimPrice) return EMPTY_SERIES;

  const mid = anchorPrice(project, book);
  if (!(mid > 0)) return EMPTY_SERIES;

  /**
   * Volatility is scaled by the timeframe: a 1W candle legitimately moves far
   * more than a 15M one. Derived from the book's spread so a wide market looks
   * wide rather than every asset having identical texture.
   */
  const spread =
    book?.asks[0] && book?.bids[0]
      ? Math.abs(usdgToNumber(book.asks[0].pricePerUnit) - usdgToNumber(book.bids[0].pricePerUnit)) / mid
      : 0.04;
  const step = Math.max(spread, 0.01) * Math.sqrt(intervalMs / TIMEFRAMES['1H'].intervalMs);

  /**
   * Milestone fraction: how far through the project's life "now" sits, taken
   * from the funding deadline. Used to bend the series toward the current price
   * so history is not a flat random walk disconnected from the project state.
   */
  /** Built oldest-first so timestamps ascend, which is what an axis assumes. */
  const candles: Candle[] = [];
  let price = mid;

  for (let i = count - 1; i >= 0; i -= 1) {
    const t = end - i * intervalMs;

    // A mild upward drift for in-production projects, flat for funding ones,
    // so the shape of the chart reflects the project's actual status.
    const drift =
      project.status === 'IN_PRODUCTION' ? 0.00035 : project.status === 'COMPLETED' ? 0.00015 : 0;

    const close = price;
    const open = i === count - 1 ? price * (1 - (rng() - 0.5) * step) : price / (1 + (rng() - 0.5) * step);
    const high = Math.max(open, close) * (1 + rng() * step * 0.6);
    const low = Math.min(open, close) * (1 - rng() * step * 0.6);
    const volume = Math.round((0.4 + rng()) * (project.claimsCommitted ? Number(project.claimsCommitted) * 0.004 : 200));

    // `i` descends, so time ascends: push keeps the array oldest-first.
    candles.push({
      t,
      o: Number(open.toFixed(6)),
      h: Number(high.toFixed(6)),
      l: Number(low.toFixed(6)),
      c: Number(close.toFixed(6)),
      v: Math.max(volume, 1),
    });

    // Step backwards: this candle's open is the previous candle's close.
    price = open / (1 + drift);
  }

  /**
   * Pin the final close to the live mid so the rightmost candle is the price the
   * stat ribbon reports. Done after generation rather than during, so the whole
   * series does not inherit the correction.
   */
  const last = candles[candles.length - 1];
  if (last) {
    const delta = mid - last.c;
    last.c = Number(mid.toFixed(6));
    last.h = Number(Math.max(last.h, last.c).toFixed(6));
    last.l = Number(Math.min(last.l, last.c).toFixed(6));
    // Shift the tail gently so the correction does not appear as a cliff.
    if (Math.abs(delta) > 0) {
      for (let i = Math.max(0, candles.length - 6); i < candles.length - 1; i += 1) {
        const c = candles[i];
        if (!c) continue;
        const weight = (i - (candles.length - 6)) / 5;
        c.c = Number((c.c + delta * weight).toFixed(6));
        c.h = Number(Math.max(c.h, c.c).toFixed(6));
        c.l = Number(Math.min(c.l, c.c).toFixed(6));
      }
    }
  }

  /**
   * Milestone markers, placed at the candle nearest their real timestamp. The
   * old chart hardcoded these at `left-1/4` and `left-2/3`, which drifted out of
   * sync with any candle that moved.
   */
  const first = candles[0]?.t ?? end;
  const span = Math.max(end - first, 1);

  const markers: MilestoneMarker[] = project.milestones
    .map((milestone) => {
      const at = new Date(milestone.approvedAt ?? milestone.dueAt).getTime();
      return {
        index: milestone.index,
        title: milestone.title,
        t: at,
        status: milestone.status,
      };
    })
    .filter((marker) => Number.isFinite(marker.t) && marker.t >= first && marker.t <= end + intervalMs)
    .map((marker) => ({
      ...marker,
      // Snap to the candle boundary so the pin aligns with a bar exactly.
      t: first + Math.round(((marker.t - first) / span) * (candles.length - 1)) * intervalMs,
    }));

  return { candles, markers, intervalMs, count: candles.length };
}

/** Highest high across a series; used for axis scaling. */
export function seriesHigh(candles: Candle[]): number {
  return candles.reduce((max, candle) => (candle.h > max ? candle.h : max), 0);
}

/** Lowest low across a series; used for axis scaling. */
export function seriesLow(candles: Candle[]): number {
  if (candles.length === 0) return 0;
  return candles.reduce((min, candle) => (candle.l < min ? candle.l : min), Infinity);
}

/** Peak volume, for scaling the volume histogram. */
export function seriesMaxVolume(candles: Candle[]): number {
  return candles.reduce((max, candle) => (candle.v > max ? candle.v : max), 0);
}

/**
 * Renders an axis label at a given interval.
 *
 * 15M/1H/4H read as clock times; 1D/1W as dates. A single formatter for all
 * five would print "12:00" for a weekly candle, which is useless.
 */
export function formatCandleTime(t: number, intervalMs: number): string {
  const date = new Date(t);
  if (Number.isNaN(date.getTime())) return '—';

  if (intervalMs <= 4 * 60 * 60_000) {
    return new Intl.DateTimeFormat('en-GB', {
      hour: '2-digit',
      minute: '2-digit',
      hour12: false,
      timeZone: 'UTC',
    }).format(date);
  }

  return new Intl.DateTimeFormat('en-GB', {
    day: '2-digit',
    month: 'short',
    timeZone: 'UTC',
  }).format(date);
}

/**
 * Formats a candle's full range for the tooltip and the price header.
 *
 * Claim units now settle at whole-dollar USDG prices (a claim is a fractional
 * entitlement around a few dollars, not a fraction of a cent), so two decimals
 * is the right precision. The earlier 6-decimal formatting existed only because
 * the mock prices were still ETH-scale and rounded to $0.00 at 2 dp.
 */
export function formatCandlePrice(value: number): string {
  return value.toFixed(2);
}
